### PR TITLE
Update wercker-box.yml

### PR DESCRIPTION
**Pull request by linkyndy**
Updates RethinkDB to 2.0.1.

### CODE REVIEW

**Comment by SellJamHere** [comment]
This would be an excellent merge

**Comment by linkyndy** [comment]
Seems that I'll need to update this again, as RethinkDB's current version is now 2.0.2. Will do that soon.

**Comment by SellJamHere** [comment]
Yup :+1:

**Comment by mies** [comment]
will at least merge this in my friends

**Pull request merged**
